auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 24h
  split_queries_by_interval: 15m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  allow_structured_metadata: false

ingester:
  max_chunk_age: 1h
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      replication_factor: 1

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
