global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Updated from 8888 to 8889

  - job_name: 'dummy-data-generator'
    static_configs:
      - targets: ['dummy-data-generator:8800']
